-- AlterTable
ALTER TABLE "OngoingMatch" ALTER COLUMN "start_time" SET DEFAULT CURRENT_TIME,
ALTER COLUMN "start_time" SET DATA TYPE TIME,
ALTER COLUMN "end_time" SET DATA TYPE TIME,
ALTER COLUMN "match_date" SET DATA TYPE DATE;
