-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "rating" INTEGER NOT NULL DEFAULT 1500,
ADD COLUMN     "rating_deviation" DOUBLE PRECISION NOT NULL DEFAULT 350.0,
ADD COLUMN     "volatility" DOUBLE PRECISION NOT NULL DEFAULT 0.06;
